### flip

In [3]:
import numpy as np
# flip reverses the order of elements along an axis
arr = np.arange(1, 10).reshape(3, 3)

In [4]:
print("Original array:\n", arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print("Flip vertically (axis=0):\n", np.flip(arr, axis=0))

Flip vertically (axis=0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [6]:
print("Flip horizontally (axis=1):\n", np.flip(arr, axis=1))

Flip horizontally (axis=1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [7]:
print("Flip all axes:\n", np.flip(arr))

Flip all axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [8]:
# reversing a 1D array
one_d = np.array([1, 2, 3, 4, 5])

In [9]:
print("Flip 1D:\n", np.flip(one_d))

Flip 1D:
 [5 4 3 2 1]


### argsort

In [11]:
# argsort returns the indices that would sort an array
x = np.array([10, 2, 5, 8, 1])

In [12]:
print("Original:", x)

Original: [10  2  5  8  1]


In [13]:
indices = np.argsort(x)

In [14]:
print("Indices that would sort x:", indices)

Indices that would sort x: [4 1 2 3 0]


In [15]:
# Use indices to sort x
print("Sorted x:", x[indices])

Sorted x: [ 1  2  5  8 10]


In [16]:
# argsort on 2D array
arr2 = np.array([[3, 1, 2],
                 [6, 4, 5]])

In [17]:
print("Argsort along axis=1:\n", np.argsort(arr2, axis=1))

Argsort along axis=1:
 [[1 2 0]
 [1 2 0]]


In [18]:
print("Sorted rows:\n", np.sort(arr2, axis=1))

Sorted rows:
 [[1 2 3]
 [4 5 6]]


### any

In [20]:
# any checks if at least one element is True
bool_arr = np.array([False, False, True, False])

In [21]:
print("Any True? ->", np.any(bool_arr))

Any True? -> True


In [22]:
# With condition
arr = np.array([0, 0, 3, 0])

In [23]:
print("Any non-zero? ->", np.any(arr))

Any non-zero? -> True


In [24]:
# On 2D arrays
mat = np.array([[0, 0, 0],
                [0, 1, 0]])

In [25]:
print("Any element True? ->", np.any(mat))

Any element True? -> True


In [26]:
print("Any True along rows? ->", np.any(mat, axis=1))

Any True along rows? -> [False  True]


In [27]:
print("Any True along cols? ->", np.any(mat, axis=0))

Any True along cols? -> [False  True False]


In [28]:
# Combine with conditions
arr = np.array([10, 20, 30, 40])

In [29]:
print("Any greater than 25? ->", np.any(arr > 25))

Any greater than 25? -> True
